# Generated by Django 3.2.19 on 2023-06-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_name', models.CharField(blank=True, db_column='Station_Name', max_length=100, null=True)),
                ('station_code', models.IntegerField(db_column='Station_Code', primary_key=True, serialize=False)),
                ('line', models.CharField(blank=True, db_column='Line', max_length=100, null=True)),
                ('out_code', models.CharField(blank=True, db_column='Out_Code', max_length=100, null=True)),
                ('lat', models.FloatField(blank=True, db_column='Lat', null=True)),
                ('lng', models.FloatField(blank=True, db_column='Lng', null=True)),
            ],
            options={
                'db_table': 'station',
                'managed': True,
            },
        ),
    ]
