# Generated by Django 3.2.19 on 2023-06-20 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='station',
            options={'managed': False},
        ),
        migrations.CreateModel(
            name='Congestion',
            fields=[
                ('serial_number', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('day_of_week_division', models.CharField(blank=True, max_length=6, null=True)),
                ('line_name', models.CharField(max_length=6)),
                ('departure_station', models.CharField(blank=True, max_length=50, null=True)),
                ('division_name', models.CharField(max_length=4)),
                ('congestion_5_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_6_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_6_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_7_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_7_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_8_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_8_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_9_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_9_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_10_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_10_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_11_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_11_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_12_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_12_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_13_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_13_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_14_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_14_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_15_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_15_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_16_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_16_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_17_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_17_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_18_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_18_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_19_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_19_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_20_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_20_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_21_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_21_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_22_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_22_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_23_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_23_30', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_00_00', models.CharField(blank=True, max_length=10, null=True)),
                ('congestion_00_30', models.CharField(blank=True, max_length=10, null=True)),
                ('remark_dc', models.CharField(blank=True, db_column='REMARK_DC', max_length=60, null=True)),
                ('station_code', models.ForeignKey(db_column='station_code', on_delete=django.db.models.deletion.PROTECT, to='subway.station')),
            ],
            options={
                'db_table': 'subway_congestion',
                'managed': True,
                'unique_together': {('serial_number', 'line_name', 'division_name')},
            },
        ),
    ]
