# Generated by Django 3.2.19 on 2023-06-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0002_auto_20230620_1653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tourspot',
            fields=[
                ('serial_number', models.DecimalField(decimal_places=0, max_digits=20, primary_key=True, serialize=False)),
                ('tourspot_name', models.CharField(blank=True, db_column='Tourspot_Name', max_length=100, null=True)),
                ('station_name', models.CharField(blank=True, db_column='Station_Name', max_length=100, null=True)),
                ('line', models.CharField(blank=True, db_column='Line', max_length=100, null=True)),
                ('exit_number', models.CharField(blank=True, db_column='Exit_Number', max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, db_column='Remarks', max_length=1000, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=1000, null=True)),
            ],
            options={
                'db_table': 'tourspots',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='congestion',
            options={'managed': False},
        ),
    ]
