# Generated by Django 3.2.19 on 2023-06-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subway', '0003_auto_20230620_1706'),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('serial_number', models.IntegerField(db_column='Serial_Number', primary_key=True, serialize=False)),
                ('line', models.CharField(blank=True, db_column='Line', max_length=100, null=True, unique=True)),
                ('upend_station', models.CharField(blank=True, db_column='UpEnd_Station', max_length=100, null=True)),
                ('downend_station', models.CharField(blank=True, db_column='DownEnd_Station', max_length=100, null=True)),
            ],
            options={
                'db_table': 'line',
                'managed': False,
            },
        ),
    ]
